/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.gf.SmartUnitTest.service.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.gf.SmartUnitTest.service.impl.CalculatorServiceImpl;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CalculatorServiceImpl_SSTest extends CalculatorServiceImpl_SSTest_scaffolding {
// allCoveredLines:[7, 10, 15, 20, 25, 26, 27, 30]

  @Test(timeout = 4000)
  public void test_add_0()  throws Throwable  {
      //caseID:b590dcb59d742e74f99e1278154c7b0b
      //CoveredLines: [7, 10]
      //Input_0_int: 0
      //Input_1_int: 0
      //Assert: assertEquals(0, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: add
      int int0 = calculatorServiceImpl0.add(0, 0);
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_divide_1()  throws Throwable  {
      //caseID:cac78fa9da90e09763def4a58fbd14df
      //CoveredLines: [7, 25, 30]
      //Input_0_int: 0
      //Input_1_int: 1
      //Assert: assertEquals(0, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: divide
      int int0 = calculatorServiceImpl0.divide(0, 1);
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_divide_2()  throws Throwable  {
      //caseID:44cdb72c904bd9ac0294eb295c031efc
      //CoveredLines: [7, 25, 26, 27]
      //Input_0_int: 0
      //Input_1_int: 0
      //Assert: assertEquals((-1), method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: divide
      int int0 = calculatorServiceImpl0.divide(0, 0);
      
      //Test Result Assert
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test_minus_3()  throws Throwable  {
      //caseID:65629259dcffdb7ebc56a3558ed592bb
      //CoveredLines: [7, 15]
      //Input_0_int: 1
      //Input_1_int: 1
      //Assert: assertEquals(0, method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: minus
      int int0 = calculatorServiceImpl0.minus(1, 1);
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_multiply_4()  throws Throwable  {
      //caseID:d695041a85b22656586137ae7a9f577e
      //CoveredLines: [7, 20]
      //Input_0_int: -1
      //Input_1_int: 4070
      //Assert: assertEquals((-4070), method_result);
      
      CalculatorServiceImpl calculatorServiceImpl0 = new CalculatorServiceImpl();
      
      //Call method: multiply
      int int0 = calculatorServiceImpl0.multiply((-1), 4070);
      
      //Test Result Assert
      assertEquals((-4070), int0);
  }
}
