/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.gf.SmartUnitTest.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.gf.SmartUnitTest.controller.CalculatorController;
import com.gf.SmartUnitTest.service.CalculatorService;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CalculatorController_SSTest extends CalculatorController_SSTest_scaffolding {
// allCoveredLines:[12, 20, 25, 30, 35]

  @Test(timeout = 4000)
  public void test_add_0()  throws Throwable  {
      //caseID:ea1702e68d77fe8c61a96a22e56ec056
      //CoveredLines: [12, 20]
      //Input_0_int: 3
      //Input_1_int: 3
      //Assert: assertEquals(3, method_result);
      
      CalculatorController calculatorController0 = new CalculatorController();
      //mock calculatorService0
      CalculatorService calculatorService0 = mock(CalculatorService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(3).when(calculatorService0).add(anyInt() , anyInt());
      
      PrivateAccess.setVariable((Class<?>) CalculatorController.class, calculatorController0, "calculatorService", (Object) calculatorService0);
      
      //Call method: add
      int int0 = calculatorController0.add(3, 3);
      
      //Test Result Assert
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test_divide_1()  throws Throwable  {
      //caseID:e0f197ad48e7b1068378a2f4fe5d4515
      //CoveredLines: [12, 35]
      //Input_0_int: 0
      //Input_1_int: 7
      //Assert: assertEquals(0, method_result);
      
      CalculatorController calculatorController0 = new CalculatorController();
      //mock calculatorService0
      CalculatorService calculatorService0 = mock(CalculatorService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      PrivateAccess.setVariable((Class<?>) CalculatorController.class, calculatorController0, "calculatorService", (Object) calculatorService0);
      
      //Call method: divide
      int int0 = calculatorController0.divide(0, 7);
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_minus_2()  throws Throwable  {
      //caseID:2fa5898c9c85a76743ae4678cfb56b6f
      //CoveredLines: [12, 25]
      //Input_0_int: 0
      //Input_1_int: 0
      //Assert: assertEquals(0, method_result);
      
      CalculatorController calculatorController0 = new CalculatorController();
      //mock calculatorService0
      CalculatorService calculatorService0 = mock(CalculatorService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(0).when(calculatorService0).minus(anyInt() , anyInt());
      
      PrivateAccess.setVariable((Class<?>) CalculatorController.class, calculatorController0, "calculatorService", (Object) calculatorService0);
      
      //Call method: minus
      int int0 = calculatorController0.minus(0, 0);
      
      //Test Result Assert
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test_multiply_3()  throws Throwable  {
      //caseID:2d83d04811c785bdf17fca6cab3e69c2
      //CoveredLines: [12, 30]
      //Input_0_int: -1
      //Input_1_int: 1
      //Assert: assertEquals(0, method_result);
      
      CalculatorController calculatorController0 = new CalculatorController();
      //mock calculatorService0
      CalculatorService calculatorService0 = mock(CalculatorService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      PrivateAccess.setVariable((Class<?>) CalculatorController.class, calculatorController0, "calculatorService", (Object) calculatorService0);
      
      //Call method: multiply
      int int0 = calculatorController0.multiply((-1), 1);
      
      //Test Result Assert
      assertEquals(0, int0);
  }
}
